### PR TITLE
Update the install diagram to reflect z/OSMF workflow changes

### PR DESCRIPTION
**Pull request by nannanli**
#### Is there a related issue for this PR? 
Issue number: 

#### Developer's Certificate of Origin (DCO)

Signed-off-by: nannanli <nannanli@cn.ibm.com> 

Updates: 
- Reorganized several related sections to distinguish the two methods (use shell scripts/JCL, use z/OSMF workflow)
- Updated the clickable diagram to add z/OSMF workflow as a new method
- Fixed several typos, links, formatting issues, etc. 

You can run a local doc site to view the changes. See [instructions](https://github.com/zowe/docs-site#previewing-or-testing-the-doc-site-locally).

### CODE REVIEW

**Comment by nannanli** [comment]
@sn666239 Hi Shreemala, could you review this PR as well?  Mainly architectural changes to reflect the new install and configure method with z/OSMF workflow. Thanks!

**Comment by Joe-Winchester** [comment]
@nannanli and @sn666239 - There is a z/OSMF workflow available for the step "Install the Zowe runtime" as you've shown in the diagram, however I don't think there are z/OSMF workflows for any of Stage 3:.    I am not aware of a workflow that is able to replace the need for ZWESECUR, or zowe-setup-certificates.sh, or zowe-configure-instance.sh.   @vit-tomica - which elements of the install/configure currently have workflows available ?  Tks  

image

**Comment by vit-tomica** [comment]
Hi Joe, there are workflows for all three steps:
- ZWESECUR - https://github.com/zowe/zowe-install-packaging/blob/master/workflows/templates/ZWESECUR.xml
- zowe-setup-certificates.sh - https://github.com/zowe/zowe-install-packaging/blob/master/workflows/files/ZWEWRF05.xml
- zowe-configure-instance.sh - https://github.com/zowe/zowe-install-packaging/blob/master/workflows/files/ZWEWRF03.xml

**Comment by sn666239** [comment]
@Joe-Winchester @nannanli Ashley has merged the pull requests created by me for all those configuration steps. We have one more unpublished workflow that is created by our devs that is configuring cross memory service with z/OSMF. Once this is published, we can create a separate page that is Configure Zowe with z/OSMF workflows.

**Comment by nannanli** [comment]
> @Joe-Winchester @nannanli Ashley has merged the pull requests created by me for all those configuration steps. We have one more unpublished workflow that is created by our devs that is configuring cross memory service with z/OSMF. Once this is published, we can create a separate page that is Configure Zowe with z/OSMF workflows.

Agree. When z/OSMF workflows can complete all the configure tasks, we can create a separate chapter for it and move the currently scattered z/OSMF sections to be separate topics under **Configure Zowe with z/OSMF workflows**. Then, update the diagram to make the two methods separate threads.

**Comment by Joe-Winchester** [comment]
> > @Joe-Winchester @nannanli Ashley has merged the pull requests created by me for all those configuration steps. We have one more unpublished workflow that is created by our devs that is configuring cross memory service with z/OSMF. Once this is published, we can create a separate page that is Configure Zowe with z/OSMF workflows.
> 
> Agree. When z/OSMF workflows can complete all the configure tasks, we can create a separate chapter for it and move the currently scattered z/OSMF sections to be separate topics under **Configure Zowe with z/OSMF workflows**. Then, update the diagram to make the two methods separate threads.

That sounds like the perfect thing to do.  Thanks to @vit-tomica for clarifying that there is a workflow for ZWESECUR and to @sn666239 for working on an doc chapter to describe this.  It's prob best as you say to to merge this PR now, then once the update for the ZWESECUR workflow is available update the diagram to link to that chapter.  Tks

**Pull request merged**
