### PR TITLE
docs: Update description about node v8.16.1 issue and workaround in v1.7.x

### PR DESCRIPTION
**Pull request by nannanli**
Signed-off-by: nannanli <nannanli@cn.ibm.com>

Node 8.16.2 is available which fixes the 8.16.1 issue so update the docs to remove the ref to need 8.16.0

#### Is there a related issue for this PR? 
Issue number: #890 

#### Developer's Certificate of Origin (DCO)

Signed-off-by: nannanli <nannanli@cn.ibm.com>

Node 8.16.2 is available which fixes the 8.16.1 issue so update the docs to remove the ref to need 8.16.0

### CODE REVIEW

**Comment by Joe-Winchester** [comment]
@nannanli - should this also go into docs-staging ?

**Comment by nannanli** [comment]
@Joe-Winchester Yes, another PR makes the changes to docs-staging. See #895 . There are different PRs that removes the reference in different versions. 
- #896 v1.7.x
- #897 v1.6.x
- #895 v1.8.0 (docs-staging)

**Comment by 1000TurquoisePogs** [comment]
8.16.1 is still not supported however, so that could cause a problem for us if we don't state that.
8.16.2 works great though.

**Comment by nannanli** [comment]
@1000TurquoisePogs With that stated, shall we update the workaround description to guide users to use v8.16.2 or later? Such as: 

**Workaround:** Use node v8.16.2 or later which is available at [https://www.ibm.com/ca-en/marketplace/sdk-nodejs-compiler-zos](https://www.ibm.com/ca-en/marketplace/sdk-nodejs-compiler-zos). Download the `ibm-trial-node-v8.16.2-os390-s390x.pax.Z` file.

**Comment by Joe-Winchester** [comment]
@nannanli - yes I like your para to let users know to use 8.16.2 or later.   Thank you

**Comment by 1000TurquoisePogs** [comment]
Just need to state that we don't support v12 yet either (soon!)

**Comment by nannanli** [comment]
@Joe-Winchester @1000TurquoisePogs The node.js support descriptions have been updated. 
- Added back the known issue with node v8.16.1 for 8.16.1 is still not supported.
- Updated the workaround to guide users to use and download v8.16.2.
- State that v12 is not supported yet. We'll need to revisit this statement when v12 is supported.

**Pull request merged**
