### PR TITLE
Architecture diagram for multitenancy configuration

### PR DESCRIPTION
**Pull request by arxioly**
Describe your pull request here:
Added multitenancy architecture diagram and description, did some corrections, and removed duplicated sentences.

List the file(s) included in this PR:
api-mediation-multi-tenancy.md
using-api-mediation-layer.md

### CODE REVIEW

**Review by balhar-jakub — APPROVED** [review]
Good job with the diagrams. Thanks

**Review by janan07 — APPROVED** [review]
Reviewed and edited by doc squad

**Comment by balhar-jakub** [comment]
Can we also apply to master? This should be already available.

**Comment by janan07** [comment]
> Can we also apply to master? This should be already available.
I think it makes sense to apply to master if this should go live now, but this will go to master in v2.16 which I thought was any day now...

**Pull request merged**
