### PR TITLE
Move code guidelines to docs-site

### PR DESCRIPTION
**Pull request by BrandonJenkins14**
I moved the "Code Guidelines" from Zowe.org to docs-site for #550 . I copied the content, added to TOC under Contributing, and spent time reviewing/adding to the text. **Please review the content itself and make changes as you see fit**. 

Not quite ready to merge, first some questions to answer -

- There seems to be some inconsistency in regards to which headings are bolded in the left-hand TOC when first opening each navigation section. Sometimes the top topic is highlighted by default, other times there are multiple topics highlighted by default. I haven't found a pattern yet. Please build and let me know if you notice the same issue. 

- I am not sure that Contributing is the place for this, or that we need both Contributing and Extending sections in general. I will do some experimentation in another branch and see if combining these sections with our tutorials under one "Contributing" section would make sense. Will open another PR for discussion.

### CODE REVIEW

**Comment by nannanli** [comment]
Hi Brandon, thanks for making the changes! For the two questions you have, here are my thoughts/findings: 
1. Not sure if it's the same screen you saw. Looks as expected on my side. :)
WeChat Screenshot_20190521143134

2. For this one, Contributing and Extending have some slight differences as I understand. 
    - Contributing is for various contributors. They could simply fix a bug and open a pull request or add new features to Zowe. Therefore, they need some guidelines or recommendations on how to work with code, UI, doc, etc to get involved. It's not "how to develop and contribute plug-in to Zowe" but instead "what I could do and how to do it to participate in this project". 
    - Extending is for the plug-in developers, kind of a developer guide that talks about how to develop on Zowe. Extenders are not necessarily contributors. They could develop a plug-in for use internally within their enterprise or choose to ontribute it back to the community. 

   Therefore, they are two sepatae sections at first. However, we coud always look at solutions to make this much clearer.

**Comment by JamesBauman** [comment]
Hi @nannanli Ashley - 

Re point 1, i believe all the top level headings in the TOC should be bold - in this case, the heading UI Guidelines is not.  on a related note, I am observing similar behavior in other sentions; not just contributing, See https://zowe.github.io/docs-site/latest/getting-started/overview.html and https://zowe.github.io/docs-site/latest/user-guide/installandconfig.html.   I'm not sure what is the solution, perhaps its the syntax in the config.js file (??).

**Comment by jackjia-ibm** [comment]
@BrandonJenkins14 I made a change to disable the bold on sidebar. Please see if this is as you expected.

**Comment by jackjia-ibm** [comment]
@BrandonJenkins14 I see. I've reverted the change.

Just to clarify, in this picture
Screen Shot 2019-05-21 at 1 59 23 PM,
there are two "Release Notes", do you mean the first "Release Notes" text? I think vuepress render it as a sidebar group, it's not clickable like the second one.

If that's correct, we need to change the way how sidebar group is rendered. I agree it looks more complicated, a separated issue will be better to track it.

**Pull request merged**
