### PR TITLE
[z/OSMF Workflow] Information on how to install zowe runtime with z/OSMF workflows

### PR DESCRIPTION
**Pull request by sn666239**
Added a new procude on how to install runtime with z/OSMF workflows.

### CODE REVIEW

**Comment by nannanli** [comment]
@sn666239 This is a new method to install Zowe runtime, so I suggest the structure of the install runtime section be modified as follows to clarify this: 

## Installing the Zowe runtime
You can install the Zowe runtime by using one of the following methods. 
- Use the zowe-install.sh script
- Use the z/OSMF workflow

### Method 1: Install the Zowe runtime with the zowe-install.sh script

The first installation step is to create a USS folder that contains the Zowe runtime artifacts.  This is known as the `<RUNTIME_DIR>`.
#### Step 1: Locate the install directory
......

### Method 2: Install the Zowe runtime with the z/OSMF workflow
z/OSMF workflow simplifies the procedure to create a runtime environment from the Zowe convenience build.
......

Other updates look good to me. cc @Joe-Winchester for any comments or feedback.

**Comment by sn666239** [comment]
Added a sentence about 2 otpions for installing runtime with shell script and z/OSMF Workflow.

**Comment by nannanli** [comment]
Hi @sn666239, I tweaked the titles and added a toc at the beginning of the topic via a direct commit. See [this commit](https://github.com/zowe/docs-site/pull/1190/commits/760ae3f3bc1ee454505af5d23264383de5b37769).

**Comment by Joe-Winchester** [comment]
@nannanli - this is a really great update to the install guide from @sn666239 with good new content and clearer flow through the install.  Do you want to do a last minute check and then merge or shall I merge it ?

**Pull request merged**
