### PR TITLE
Renamed zlux-example-server and  zlux-proxy-server

### PR DESCRIPTION
**Pull request by jhenryRocket**
Renamed zlux-example-server to zlux-app-server (includes one file name change and a change to the config.js) Also renamed zlux-proxy-server to zlux-server-framework

### CODE REVIEW

**Comment by nannanli** [comment]
Hi Julie, @jhenryRocket One comment: Is this for 1.0 or 0.9.5? If it's for 1.0, can you open the PR against the `docs-staging` branch and add release notes for this change? Thanks!

**Comment by jhenryRocket** [comment]
These name changes are for 1.0.

**Comment by jhenryRocket** [comment]
Closing this pull request as these changes should go into 1.0.

**Comment by jhenryRocket** [comment]
I'm re-opening this PR because the name changes are currently available. See https://github.com/zowe/zlux-app-server. I will close the open PR for 1.0. Sorry for the confusion!

**Pull request merged**
