### PR TITLE
Update to Docusaurus v3

### PR DESCRIPTION
**Pull request by t1m0thyj**
**Describe your pull request here:** Update the docs site from Docusaurus v2 to v3 (see [release notes](https://docusaurus.io/blog/releases/3.0)).

Some swizzled components had to be updated - in particular `NotFound` and `ZoomedImage`. In Docusaurus v3 custom component names must start with an uppercase letter, so renamed `tpsr` -> `Tpsr` and `image` -> `Image`.

Versioned sidebar json files were updated because Docusaurus v3 removed support for version prefixes.

There are a lot of .md files changed in this PR because Docusaurus updated their .md parser to be more strict. The changes should be only cosmetic and have negligible effect on content, but please review them 🙂 

* Indented code blocks are no longer supported. Code blocks must now be surrounded by triple ticks.
* The following characters are not permitted unless they are escaped or inside a code block: `<`, `>`, `{`, `}`
  * In most places I have surrounded words/phrases that contain these characters in code blocks
  * To escape these characters, you can prefix them with a backslash (e.g., `{` -> `\{`)

**List the file(s) included in this PR:** A lot

_After creating the PR, follow the instructions in the comments._

### CODE REVIEW

**Review by anaxceron — APPROVED** [review]
Thanks for doing this upgrade!

**Comment by anaxceron** [comment]
This looks great, Timoteo (aka @t1m0thyj) -- thank you for all your help!

**Comment by anaxceron** [comment]
NOTE: This PR also changes the **PDF** link at the top of every article to **Print**.

We made this change b/c the PDF link opened up a PDF document of the entire Zowe Docs site. The **Print** link creates a document of _only_ the target article (meaning, the article from which the user clicked the **Print** link). This way, a user can either print or create a PDF document of the article in context.

**Review by traeok — APPROVED** [review]
LGTM, thanks for the technical currency @t1m0thyj!

**Pull request merged**
