### PR TITLE
Release 1.6.0 

### PR DESCRIPTION
**Pull request by BrandonJenkins14**
This PR is for the Release of Zowe 1.6.x documentation. 
- Updated version numbers 
- Added placeholders for each component Release Notes
- To update TPSRs at release time

### CODE REVIEW

**Comment by zFernand0** [comment]
> @zFernand0 Do you know if any new features/enhancements/fixes have made it into @lts-incremental or @latest recently? For v1.6.0 we have nothing documented in Release Notes, and for @latest version we have the following documented: https://github.com/zowe/docs-site/blob/active-development/docs/getting-started/summaryofchanges.md#version-highlights

@BrandonJenkins14, The only think I can think of is: https://github.com/zowe/zowe-cli/pull/546

Because of a security vulnerability on imperative it was not able to be published two days ago, but that has been resolved in by: https://github.com/zowe/zowe-cli/pull/550

So, you can expect a `2.32.0` coming soon :smile:

**Comment by zFernand0** [comment]
> @zFernand0 @ChrisBoehmCA I just added a a RN entry for the WFO/WFA options, but I'm not sure if I accurately portrayed how it works. Can you take a look when you get a chance? Thanks!

https://github.com/zowe/docs-site/blob/docs-staging/docs/getting-started/summaryofchanges.md#whats-new-in-zowe-cli
Took me a bit to find what I was looking for :smile:

**Comment by ChrisBoehmCA** [comment]
Release notes look pretty good, but instead of "or return output"  , I would say "or complete and enter OUTPUT status." Because just specifying --wfo does not return any spool output, it just waits for the job to finish

**Comment by jackjia-ibm** [comment]
DCO sign-off should/will be addressed offline to update dco signoff folder.

**Pull request merged**
