### PR TITLE
Fixed Typo start-zowe-zos.md

### PR DESCRIPTION
**Pull request by kirkster96**
Describe your pull request here:

https://www.ibm.com/docs/en/zos/3.1.0?topic=sc-syntax-30

fixed typo

List the file(s) included in this PR:
start-zowe-zos.md

After creating the PR, follow the instructions in the comments.

### CODE REVIEW

**Review by janan07 — APPROVED** [review]

**Review by balhar-jakub — APPROVED** [review]

**Review by pablocarle — APPROVED** [review]

**Review by janan07 — APPROVED** [review]
reviewed by doc squad

**Pull request merged**
