### PR TITLE
Generating PDF in build pipeline

### PR DESCRIPTION
**Pull request by jackjia-ibm**
@PlutoZhang @nannanli  I have embedded the generating pdf step into current build pipeline. For each docs build, the build HTML result which goes into `.deploy/latest/`, and the PDF will be placed as `.deploy/latest/Zowe_User_Guide.pdf`.

If you want to generate PDF in your local machine, you can run `npm run docs:pdf` command. For more detail instructions, please check out the `docs/.pdf/README.md`.

If it's master branch, the PDF generated will be published automatically to https://zowe.github.io/docs-site/ along as HTML build result. The download URL is https://zowe.github.io/docs-site/latest/Zowe_User_Guide.pdf. (I've removed the old docs/.vuepress/public/Zowe_User_Guide.pdf from code base.)

The PDF generated looks similar to Zowe_User_Guide_0.9.4.pdf, but has all the pages. This is the test result generated on my local: [Zowe_User_Guide.pdf](https://github.com/zowe/docs-site/files/2673327/Zowe_User_Guide.pdf)

To define pages, I've added a new variable `ALL_PAGES` in `docs/.vuepress/config.js`, and also code to generate variables for navbar and sidebar. So `ALL_PAGES` will be the place if we want to re-organize pages, add new or remove pages.

Please let me know if you find issues. Thank you!

### CODE REVIEW

**Comment by nannanli** [comment]
Thanks Jack @jackjia-ibm ! 
I went through the sample PDF output and spotted the following issues. Some are the same as Pluto found. Could you help check if there is a way to improve them? 
- The graphics exceed page border. For example, the graphics on Page 56 and Page 57.
- The problem with conversion of tables seems to persist in some pages. For example, on P22 and P23-24, the tables are in MD. However, on some other pages, it works well (like P49-51). 
- The display of some vuepress supported tags are not converted as expected. For example, `:::warning`, `:::Tip`. I'm looking into dita-ot doc to check some tips but you might have some insights about this.

**Comment by jackjia-ibm** [comment]
Thanks @PlutoZhang and @nannanli. I've fixed the table issue. Here is the latest PDF: 
[Zowe_User_Guide.pdf](https://github.com/zowe/docs-site/files/2676913/Zowe_User_Guide.pdf)

For questions:

> Could the previous Zowe_User_Guide.ditamap used to build PDF file be deprecated?
>> Yes I think after we merged this into master, we can deprecated the old ditamap. The new ditamap is generated from constant defined in config.js.

> As for the title of the new PDF of the whole docs site including extending and contributing, we may need to change to a proper one.
>> @nannanli do you recommended subtitle and meta information for the PDF file? I can put them into the ditamap.

For other issues in the PDF, I need to investigate if there are ways to fix it. Will keep you guys posted.

**Comment by nannanli** [comment]
@jackjia-ibm 
Thanks for rendering the table. I spotted another two ill-formatted tables and fixed them in the same way as you did. 

For this question: 
> do you have recommended subtitle and meta information for the PDF file? I can put them into the ditamap.

Because the PDF now is for the whole doc site doc, I suggest we use the following information on the PDF cover
```
Open Beta for Zowe
Zowe documentation
Version 0.9.x
```
I believe there is a place we can modify the version number for each release, right? Jack, I'd like to invite you to one of our future doc meetings to give us some education about this new PDF generation mechanism. Many folks will be out next week so I'll invite you to one of the January meetings. Thanks much!

**Comment by jackjia-ibm** [comment]
Thanks @nannanli for the fixes.

I've updated the subtitle, also renamed the PDF to "Zowe_Documentation.pdf". Please let me know if this looks ok or not:
[Zowe_Documentation.pdf](https://github.com/zowe/docs-site/files/2681465/Zowe_Documentation.pdf)

Currently on docs-site, there is no current Zowe version defined. So I added this constant `CURRENT_ZOWE_VERSION` to `docs/.vuepress/config.js`. In the future, we need to update this version along with Zowe release.

**Pull request merged**
