### PR TITLE
Security commands to read z/OSMF keyring

### PR DESCRIPTION
**Pull request by plavjanik**
Signed-off-by: Petr Plavjanik <petr.plavjanik@broadcom.com>

Resolves https://github.com/zowe/zowe-install-packaging/issues/231

### CODE REVIEW

**Comment by Colin-Stone** [comment]
okay am on it, need to create a support ticket so unlikely to completed today

**Comment by plavjanik** [comment]
Top Secret commands were tested on Broadcom systems

**Comment by Colin-Stone** [comment]
Please wait until the commands are tested before putting into documentation. I am awaiting IBM SysProgs to confirm they have run the command at which stage I can do this.

**Comment by nannanli** [comment]
@Colin-Stone Hi Colin, I tentatively reverted the merge. When you get confirmation, I'll revert this 'revert` to include the changes in documentation. Thanks!

**Comment by Colin-Stone** [comment]
So I have had those permissions added to my own id but still get the failed response when running the script i.e.
keytool: trust_zosmf 7: scripts/apiml_cm.sh 445: FSUM9209 cannot execute: reason code = 0b1b03d1: EDC5139I Operation not permitted.
This is as I say my own id with the permissions rather than a super user id. Should I try that next?.

**Comment by plavjanik** [comment]
Hi Colin, can you please try the latest version of the `apiml_cm.sh` script(https://github.com/zowe/api-layer/blob/master/scripts/apiml_cm.sh)? It has removed the need for superuser.

**Comment by Colin-Stone** [comment]
I copied and pasted the content into my 0.9.6 installation but still same result:
/u/stonecc/zowe/0.9.6/api-mediation:>scripts/apiml_cm.sh --action trust-zosmf --zosmf-keyring IZUKeyring.IZUDFLT --zosmf-userid IZUSVR
Listing entries in the z/OSMF keyring (IZUKeyring.IZUDFLT):
keytool error: java.lang.Exception: Keystore does not exist: safkeyring://IZUSVR/IZUKeyring.IZUDFLT
It is not possible to execute commands as z/OSMF user ID IZUSVR. The effective user ID was: STONECC. You need to run this command as user that has access to the z/OSMF keyring or as a superuser:
  cd /u/stonecc/zowe/0.9.6/api-mediation
  scripts/apiml_cm.sh --action trust-zosmf --zosmf-keyring IZUKeyring.IZUDFLT --zosmf-userid IZUSVR

**Comment by John-A-Davies** [comment]
@Colin-Stone Looks like STONECC needs access to the zosmf keyring.  The zosmf doc tells you how to share the keyring with Liberty, but not a private userid like STONECC.

**Pull request merged**
