### PR TITLE
Error codes and troubleshooting CLI plug-ins

### PR DESCRIPTION
**Pull request by anaxceron**
Created a new page on **Troubleshooting Zowe CLI plug-ins**. 

This includes:

- a brief/generic message advising users on back-end vendor error codes 
- steps to research issues while troubleshooting

Including the whole team as reviewers b/c we discussed this while triaging [Issue 1611](https://github.com/zowe/docs-site/issues/1611) back in December.

### CODE REVIEW

**Review by gejohnston — APPROVED** [review]
This will help direct people who do not consider the real source of their problem before they ask for help.

**Review by adam-wolfe — APPROVED** [review]
LGTM

**Review by zFernand0 — APPROVED** [review]
The contents looks great!
I'm curious to know if you (@Joe-Winchester) agree that this is a good first step towards addressing the DB2 error code issue posted in the docs-site repo.
- https://github.com/zowe/docs-site/issues/1611

**Review by traeok — APPROVED** [review]
LGTM!

**Review by ATorrise — APPROVED** [review]
LGTM💸

**Pull request merged**
