### PR TITLE
Clarify the unpax instructions

### LINKED ISSUE #728: Doc should say scripted XMEM install un-paxes zss.pax
## Description

Section "Creating the xmem-server/zss directory" tells the user to un-pax the zss.pax file, but this is done for you by the `xmem-server/zowe-install-apf-server.sh` script.  The way the doc is arranged leads the reader to think that they must un-pax first, then perform either a manual or scripted install of xmem-server.  This is not correct.

  

## Expected behavior

The un-pax instructions should be moved to be under the "Manually..." heading, and the "Scripted..." paragraph should explain that the script does the un-pax for you.

### PR DESCRIPTION
**Pull request by nannanli**
#### Is there a related issue for this PR? 
Issue number: Fixes #728 

#### Developer's Certificate of Origin (DCO)

Signed-off-by: nannanli <nannanli@cn.ibm.com>

#### Description
Clarified that the manual installation requires unpax of the `zss.pax` file. The scripted installation will create the directory using the script. Also fixed a link in the doc.

### CODE REVIEW

**Comment by nannanli** [comment]
Thanks @John-A-Davies ! All comments are fixed. The link uses an .html extension so it does not work in Markdown. Have fixed it to use .md. Also updated the STC subcomponent names to add two missing ones. Would you please confirm if everything is good now?

**Comment by nannanli** [comment]
> OK but another change is required.
> 
> Replace `you must add PPT entries for the server and address spaces to the SCHEDxx member of the system PARMLIB. To add PPT entries, you can issue the following commands:`
> with
> `Add the following PPT entries for the server and address spaces to the SCHEDxx member of the system PARMLIB. `

@John-A-Davies Done. : )

**Comment by Joe-Winchester** [comment]
@nannanli - I saw these changes have been merged into master.  How does docs-staging get kept up to date ?   Does this need to be also pushed to docs-staging as that's the branch I tend to create PR branches from ?   Tks

**Comment by nannanli** [comment]
@Joe-Winchester Hi Joe, `docs-staging` is created based on `master` (docs-staging = content on master + content for new features/enhancements) and here is how we manage changes between the two branches: 

- If it's a doc bug fix or small doc enhancement, we merge the changes to `master`. 
- If it's doc for new features or relatively large doc enhancements, we merge PRs to `docs-staging`. 
- We sync changes from `master` to `docs-staging` time to time to keep docs-staging up to date with master. (using git pull)

I think I understand what your concern is now. If we do not merge the changes from master to docs-staging in time and people create PRs from docs-staging during that time, then there might be conflict when it's merged to master. We'll need to ensure that when a doc fix is merged to master, we immediately sync that to docs-staging as well to keep content up to date. Does this help?

**Pull request merged**
