### PR TITLE
Apiml start script variables

### PR DESCRIPTION
**Pull request by jandadav**
changes for latest round of externalized variables

### CODE REVIEW

**Comment by jandadav** [comment]
@janan07 Hello Andrew, hope you had great Easter! Would you find time to look at this PR please?

**Comment by jandadav** [comment]
Hi @janan07, are there additional changes or is your review complete?

**Review by janan07 — APPROVED** [review]
Reviewed and edited by tech info

**Comment by jandadav** [comment]
> Reviewed and edited by tech info

Much appreciated!

**Pull request merged**
