### PR TITLE
Zis plugin attributes

### PR DESCRIPTION
**Pull request by DivergentEuropeans**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../docs/contribute/contributing.md) to this repository.

✔️ If the changes in this PR is part of the next future release, make this pull request against the **docs-staging** branch which will be published at the next release boundary. If the changes in this PR are part of the current release, use the default base branch, **master**. For more information about branches, see https://github.com/zowe/docs-site/tree/master#understanding-the-doc-branches. 
      
N/A  If this PR relates to GitHub issues in `docs-site` or other repositories, please list in Description, prefixed with **close**, **fix** or **resolve** keywords.

### Description (including links to related git issues)
This adds a small section to the existing "Packaging z/OS extensions" section to outline new, soon to be implemented ZIS plugin attributes

:heart:Thank you!

### CODE REVIEW

**Comment by DivergentEuropeans** [comment]
Yes, do not yet merge. Subject to change too with name changes, will update soon

**Comment by DivergentEuropeans** [comment]
@nannanli Should now be safe to remove "do not merge" label (Updated & ready to merge)

**Comment by nannanli** [comment]
Can this PR be merged now?

**Comment by DivergentEuropeans** [comment]
Not yet @nannanli Thank you for asking. Will update you soon

**Review by 1000TurquoisePogs — APPROVED** [review]

**Pull request merged**
