### PR TITLE
Documentation changes for HTTPS southbound

### PR DESCRIPTION
**Pull request by plavjanik**
This PR covers updated documentation for HTTPSB feature (waffle.io/zowe/api-layer?epic=5bd8b9a84e79b4001b66225c)

### CODE REVIEW

**Comment by JamesBauman** [comment]
Hi Andrew @janan07 - We need to add the updates to the release notes for APIML.  Petr sent an email to us about 90 minutes ago detailing the enhancements,  I can take a stab at writing the changes... let me know ....

thx,
jb

**Comment by JamesBauman** [comment]
@janan07  - there are conflicts that need to be resolved.  for some reason this merge will let you resolve them using only the Git Command Line utility.  you might need help from your engineers with this.  @BrandonJenkins14 and i will take a look, but you are the expert on the content,,,,,

**Comment by nannanli** [comment]
@janan07 @JamesBauman @BrandonJenkins14 I'm looking at these conflicts. The following conflicts are caused by the relocation of topics. After doc site reorganization, these topics have been removed to the docs/extend/extend-apiml folder. I can resolve these conflicts as I'm working on the install-zos.md. Will provide an update here later.

**Comment by nannanli** [comment]
@janan07 The conflicts have been resolved and several broken links were also fixed. Please validate the changes and see if there is any problem. If all look good, can you merge this PR? Thanks!

**Pull request merged**
