### PR TITLE
Link to medium.com/zowe guidelines + external

### PR DESCRIPTION
**Pull request by Joe-Winchester**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../docs/contribute/contributing.md) to this repository.

- [x] If the changes in this PR is part of the next future release, make this pull request against the **docs-staging** branch which will be published at the next release boundary. If the changes in this PR are part of the current release, use the default base branch, **master**. For more information about branches, see https://github.com/zowe/docs-site/tree/master#understanding-the-doc-branches. 
      
- [x] If this PR relates to GitHub issues in `docs-site` or other repositories, please list in Description, prefixed with **close**, **fix** or **resolve** keywords.

### Description (including links to related git issues)
Bloggers wanted to find information on how to contribute to medium.com/zowe, so added a link in the docs to the publication guidelines.
Also included links to the youtube video channels for Mainframe Bytes (from @jellypuno) and the Zowe Demos playlist (from Bill Pereria)

:heart:Thank you!

### CODE REVIEW

**Comment by Joe-Winchester** [comment]
@jellypuno - are you OK to have a link to mainframe bytes from the videos link in the doc ?  [click to preview](https://github.com/zowe/docs-site/blob/5960601c305e6a568a04a1e91b8e7a4ca7ccdb40/docs/getting-started/zowe-resources.md)

**Review by nannanli — APPROVED** [review]
Thanks Joe for the updates! I'll approve this first so it could be merged. Will wait to see if any comments from Jessielaine and Bill.

**Comment by jellypuno** [comment]
@Joe-Winchester Yes. I would be honored! Thank you for the head's up 😊

**Comment by Joe-Winchester** [comment]
I checked with Bill who confirmed he is happy for his channel to be included in the docs:  copying his e-mail here:
```
Hi Joe,
 
Sure i'm ok and happy with that!
 
Thanks and Regards,
Bill Pereira
z/OS System Programmer, IBM Z Developer Advocate
+55 19 9 9868 9679 Mobile
billpereira@br.ibm.com
 
```

**Pull request merged**
