### PR TITLE
added a new section to configure Zowe Cross Memory Server with z/OSMF…

### PR DESCRIPTION
**Pull request by sn666239**
… workflows

Signed-off-by: Shreemala <shreemalachickmagaravalli.nagappagowda@broadcom.com>

#### Is there a related issue for this PR? 
Issue number:

### CODE REVIEW

**Comment by nannanli** [comment]
@sn666239 Hi Shreemala, this section looks good to me. With this workflow added, I assume we could separate z/OSMF workflow information as a standalone chapter now, right?

**Comment by nannanli** [comment]
I think it's best to merge this PR first and create a new one to restructure docs to make the configuration flow and the two configuration methods (using shell scripts VS using z/OSMF Workflow) clear in docs.

**Comment by sn666239** [comment]
Made changes as per suggestions. Added crosss reference (anchored) links after the first paragraph.

**Comment by sn666239** [comment]
Made changes as per suggestions

**Comment by nannanli** [comment]
Merging this PR. Will create a separate chapter for the z/OSMF workflow information.

**Pull request merged**
