### PR TITLE
Zds 1164

### PR DESCRIPTION
**Pull request by Joe-Winchester**
#### Is there a related issue for this PR? 
#1164

### CODE REVIEW

**Comment by Joe-Winchester** [comment]
Tls @stevenhorsman - I've just told users to upgrade to 1.11 for now, which means at least if they see the error with pre 1.11 they'll be able to resolve it

**Comment by NakulManchanda** [comment]
I think we can add suggestion as pointed by steve as well to docs

$INSTANCE_DIR/instance.env
ZWED_node_cluster_storageTimeout=30000

as discussed on architecture call today is not a bad idea.

**Comment by Joe-Winchester** [comment]
> we can suggest user to add this variable,
> $INSTANCE_DIR/instance.env
> ZWED_https_node_cluster_storageTimeout=30000
> as discussed today, i can verify the exact variable name

@NakulManchanda - I wasn't sure from looking at the code and also the issue whether the ZWED_http:node_cluster_storageTimeout=30000 actually is implemented and functional, or whether it was a desire to have ZLUX enhanced to do this.    If it is functional, how many other similar ZWED_ variables are available that might be interesting to doc ?

**Comment by stevenhorsman** [comment]
I decided to cut out the middle man and just pushed the fix myself

**Pull request merged**
