### PR TITLE
Update keyring setup doc

### PR DESCRIPTION
**Pull request by stevenhorsman**
Signed-off-by: stevenhorsman <steven@uk.ibm.com>

### Description
Resolves: #1413 
- Update the keyring certificate configuration doc to reference the new keyring.env file
- Add some clarity about how to run `zowe-setup-certificates.sh`

### CODE REVIEW

**Review by nannanli — APPROVED** [review]
@stevenhorsman Hi Steve, this PR looks good. Thanks for the updates! Can this PR be merged now? Do we need review from anyone?

**Comment by stevenhorsman** [comment]
I'd like a review from @Joe-Winchester - which should come with the dev PR review

**Comment by Joe-Winchester** [comment]
@nannanli - as part of my review I sort of took over this branch (after chatting to Steve) and it now contains 16 changes file.  
- keystore and keyring docs following customer feedback where there was confusion
- consolidate all chapters to get consistency for use of RUNTIME_DIR
- Added a Zowe topology diagram to explain the directories for RUNTIME_DIR, INSTANCE_DIR, KEYSTORE_DIR and their relationships
Could you please do a review as I'm sure I've made a number of mistakes and omissions and it'd be great to get your feedback.

**Review by Joe-Winchester — APPROVED** [review]

**Comment by nannanli** [comment]
@Joe-Winchester Hi Joe, I've edited the topics to fix some small issues. See my changes [here](https://github.com/zowe/docs-site/pull/1421/commits/d11ff0cb98d058447b7aa32d1870824f5302b2b1). Thanks for creating the diagrams which makes it much easier to understand the topology!

**Pull request merged**
