### PR TITLE
Zowe Explorer Known Issues

### PR DESCRIPTION
**Pull request by IgorCATech**
Signed-off-by: Igor Kazmyr <43951184+IgorCATech@users.noreply.github.com>

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../docs/contribute/contributing.md) to this repository.

- [ ] If the changes in this PR is part of the next future release, make this pull request against the **docs-staging** branch which will be published at the next release boundary. If the changes in this PR are part of the current release, use the default base branch, **master**. For more information about branches, see https://github.com/zowe/docs-site/tree/master#understanding-the-doc-branches. 
      
- [ ] If this PR relates to GitHub issues in `docs-site` or other repositories, please list in Description, prefixed with **close**, **fix** or **resolve** keywords.

### Description (including links to related git issues)
Adding a new troubleshooting section for Zowe Explorer. https://github.com/zowe/vscode-extension-for-zowe/issues/846 - issue in the ZE repo.

:heart:Thank you!

### CODE REVIEW

**Comment by IgorCATech** [comment]
The list of the known issues is not complete and will be complemented/edited as the extension grows. I lack a solution to the issue in the bottom of the list. @jellypuno or @zdmullen  would be nice to get your input. 
Also, feel free to add more known issues to https://github.com/zowe/vscode-extension-for-zowe/issues/846

**Comment by jellypuno** [comment]
**Another known issues**

Error: self signed certificate in certificate chain

Fix: Set reject-unauthorize to false

**Comment by IgorCATech** [comment]
Good catch, @BrandonJenkins14 Let me fix this one.

**Comment by IgorCATech** [comment]
@zFernand0 One question re ZE - as a user, can I enable Debug Mode so that I can get more logs to help me troubleshoot potential/existing issues?

**Comment by IgorCATech** [comment]
So far there's no solution to the binary file known issue.

**Pull request merged**
