### PR TITLE
updated typedoc and typedoc@next files

### PR DESCRIPTION
**Pull request by JamesBauman**
updated typedoc and typedoc@next files

Signed-off-by: jamesbauman <james.bauman@broadcom.com>

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../docs/contribute/contributing.md) to this repository.

- [ ] If the changes in this PR is part of the next future release, make this pull request against the **docs-staging** branch which will be published at the next release boundary. If the changes in this PR are part of the current release, use the default base branch, **master**. For more information about branches, see https://github.com/zowe/docs-site/tree/master#understanding-the-doc-branches. 
      
- [ ] If this PR relates to GitHub issues in `docs-site` or other repositories, please list in Description, prefixed with **close**, **fix** or **resolve** keywords.

### Description (including links to related git issues)
Please describe your pull request.

:heart:Thank you!

### CODE REVIEW

**Comment by JamesBauman** [comment]
@awharn  Please review

**Comment by awharn** [comment]
I took a look at this. It appears that the Next branch typedoc is missing. I also believe that the contents of the `stable` folder are supposed to be moved to a `1.25.x` directory under `static`.

**Comment by JamesBauman** [comment]
@awharn  Andrew - I am not sure how typedoc_next was removed from doc-staging.  I'll restore with a new PR.

**Comment by JamesBauman** [comment]
typedoc_next is missing from my previous commit to https://github.com/zowe/docs-site/tree/jabauman-zowe-cli-update-typedoc/static/stable.   The purpose of this PR is to restore the missing directory/files.

**Review by nannanli — APPROVED** [review]
Looks good to me!

**Comment by JamesBauman** [comment]
OK to merge per Ashley

**Pull request merged**
