### PR TITLE
Update configure-uss.md

### LINKED ISSUE #2999: Give this page a better name: docs.zowe.org/stable/user-guide/configure-uss
This page looks like someone forgot to name it in the sidebar:
image

It's an important page that might be overlooked: users need USS set up correctly to use Zowe.

### PR DESCRIPTION
**Pull request by samanthasusu**
Signed-off-by: samanthasusu <Wen.Ting.Su@ibm.com>
- rename the configure-uss.md

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../docs/contribute/contributing.md) to this repository.

- [ ] If the changes in this PR is part of the next future release, make this pull request against the **docs-staging** branch which will be published at the next release boundary. If the changes in this PR are part of the current release, use the default base branch, **master**. For more information about branches, see https://github.com/zowe/docs-site/tree/master#understanding-the-doc-branches. 
      
- [ ] If this PR relates to GitHub issues in `docs-site` or other repositories, please list in Description, prefixed with **close**, **fix** or **resolve** keywords.
fix #2999 
### Description (including links to related git issues)
Please describe your pull request.

:heart:Thank you!

### CODE REVIEW

**Comment by samanthasusu** [comment]
@1000TurquoisePogs I have checked other places with reference to this site and find out the title was there but not displayed as an article title. So I continued to use "UNIX System Services considerations for Zowe" as the title. If any further change needed, please let me know.

**Comment by samanthasusu** [comment]
Hi @janan07 @1000TurquoisePogs shall we change the title of this article by approving this PR? I saw another issue #3100  related to this. Thank you very much.

**Comment by samanthasusu** [comment]
Hi @anaxceron would you mind approving this title change pull request and I will close the issues that are related to the title? Thank you!

**Review by anaxceron — APPROVED** [review]
approved! Thanks for handling this, Sam

**Pull request merged**
