### PR TITLE
Create install roadmap V2 & update checklist.pptx

### PR DESCRIPTION
**Pull request by nellietan**
Add a V2 install roadmap draft for review
Signed-off-by: nellietan <tanzhiqian@ibm.com>

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../docs/contribute/contributing.md) to this repository.

- [ ] If the changes in this PR is part of the next future release, make this pull request against the **docs-staging** branch which will be published at the next release boundary. If the changes in this PR are part of the current release, use the default base branch, **master**. For more information about branches, see https://github.com/zowe/docs-site/tree/master#understanding-the-doc-branches. 
      
- [x] If this PR relates to GitHub issues in `docs-site` or other repositories, please list in Description, prefixed with **close**, **fix** or **resolve** keywords.
https://github.com/zowe/docs-site/issues/1619

### Description (including links to related git issues)
Please describe your pull request.

Add a V2 installation and configuration high-level roadmap **[draft for review]**
We can also work on a sub-diagram for detailed tasks such as configuring certificates.

:heart:Thank you!

### CODE REVIEW

**Comment by nellietan** [comment]
Hi @Joe-Winchester I have drafted the Zowe V2 install and config roadmap (high-level) diagram as attached for your kind review. We can work on a separate sub-diagram for more detailed config roadmap about certificate-related tasks if needed later. 

Download PDF here: https://github.com/zowe/docs-site/blob/53d2af26308bbddbea0822da72d5a1150a11a71c/docs/user-guide/Install%20roadmap%20V2.pptx

Many thanks!

**Comment by nellietan** [comment]
Hi @skurnevich 
Thank you for contributing to this! They are very helpful!!
It's a good idea to have both detailed and short versions. We will take a closer look at the flowcharts you created and post here if any updates ;)

**Review by Joe-Winchester — APPROVED** [review]
For the Zowe v1 installation roadmap we had hyperlinks from the diagram to the doc chapters that provided more detail.   Is this available in the v2 roadmap ?

**Comment by skurnevich** [comment]
Hi @Joe-Winchester 
As I can see for Zowe v1 we had a map over the image, that should be easily doable for v2 as well, however, I see some performance issues on that page so maybe there is a better way to handle that, I do not know all the Docusaurus features.
Screenshot 2023-03-21 at 19 19 58

`zwe init security` is responsible for configuring the security product, handling users, groups, etc.
certificates are handled by `zwe init certificate` and I've moved it to Stage 4 in a detailed flowchart exactly because of the reasons you've described, it is one of the pain points for customers.
Screenshot 2023-03-21 at 19 25 12
However this only links to pages that exist in docs so it does not have all the possible scenarios, I agree that this part of the installation could be described in a more granular way

And yes I agree that having an upgrade process described in docs would be a really useful enhancement.

**Comment by nellietan** [comment]
Yes we can add clickable links on the picture, and I am exploring other ways, e.g. svg format, to display the diagram to avoid usability issue of V1 diagram. We could have separate diagrams for certificates and migration.

**Comment by samanthasusu** [comment]
Will be merged together with the certificate section ready #2822

**Comment by nellietan** [comment]
(Tried with svg method to provide image with hyperlink but failed...The method used with V1 diagram also has display issues.)

Workaround is: split install and config into two diagrams under install & configure sections, so that users can get a general idea of the options and then get to the specific tasks via links below. 

Preview: https://deploy-preview-2689--zowe-docs-master.netlify.app/stable/user-guide/install-zos

Certificate diagram will be the next item after the certificate section ready https://github.com/zowe/docs-site/pull/2822

Consider working on HA and upgrade diagrams the next PI.

**Comment by nellietan** [comment]
Removed duplicate links on checklist page and reorganized the steps, e.g. consolidated the HA steps.

**Review by anaxceron — APPROVED** [review]
Looks good, Nellie, thank you!

**Pull request merged**
