### PR TITLE
Update api-mediation paths

### PR DESCRIPTION
**Pull request by stevenhorsman**
Note - this is not for the 1.5 release.

### CODE REVIEW

**Comment by nannanli** [comment]
@stevenhorsman Hi Steve, just to confirm, this is part of the V1.6 release, right?

**Comment by stevenhorsman** [comment]
Yes - this is part of 1.6

**Comment by nannanli** [comment]
Thanks Steve! The docs-staging branch is now accepting 1.6 release doc changes. We could merge this PR once Joe approves it. I took a look and fixed two minor style issues in the troubleshooting topic.

**Comment by nannanli** [comment]
@janan07 Hi Andrew, for your awareness that this affects the APIML doc.

**Comment by nannanli** [comment]
@stevenhorsman @Joe-Winchester Hi Steve, Joe, can this PR be merged now? The V1.6.0 release had been published and this is part of 1.6.

**Comment by stevenhorsman** [comment]
@nannanli - yes this can be merged

**Pull request merged**
