### PR TITLE
removing v1.28.x doc to make room for v 2.7 doc build

### PR DESCRIPTION
**Pull request by anaxceron**
Removed v1.28.x documentation to make room for v2.7 documentation

### CODE REVIEW

**Comment by balhar-jakub** [comment]
@anaxceron We need to revert this change and instead remove the 2.0 version as 1.28.3 version is maintenance version and as such supported.

**Comment by anaxceron** [comment]
@balhar-jakub I will work on this and let you know when this has been reverted.

@nannanli please advise

**Comment by balhar-jakub** [comment]
@anaxceron Thank you very much Ana.

**Comment by anaxceron** [comment]
@balhar-jakub Zowe Docs has now archived v2.0 and v2.1 documentation. The documentation for v1.28.x is now live again

**Comment by balhar-jakub** [comment]
Thank you

**Comment by zFernand0** [comment]
I wanted to follow-up on the docs-staging topic regarding the removal and addition of 1.28.x

Commit removing v1.28.x: https://github.com/zowe/docs-site/commit/04419657060777e4685b6e811f335f4de9fdf74b
Note: your browser may run out of memory if you try to get to the last 2 files.

Notice (in the GIF) that it was a very self-contained removal of 1.28.x with the exception of following 3 files:
- `docusaurus.config.js` removes 1.28.x from the exports
- `versions.json` removes v1.28.x from the list of versions
- `versionsArchived.json` adds the v1.28.x to the archive

Commit adding 1.28.x back: https://github.com/zowe/docs-site/commit/db081b2bc7684e7e32e0a330e1ce9e0a5e480b5f
And the files listed above were also updated (in a different commit) to revert the same changes. Here is the latest state of those files:
- `docusaurus.config.js` https://github.com/zowe/docs-site/blob/master/docusaurus.config.js#L218-L220
- `versions.json` https://github.com/zowe/docs-site/blob/master/versions.json#L7
- `versionsArchived.json` https://github.com/zowe/docs-site/blob/master/versionsArchived.json#L3-L4

And finally the GIF:
temp

**Pull request merged**
