### PR TITLE
[Draft] - Add a chapter to help users configure USS

### PR DESCRIPTION
**Pull request by Joe-Winchester**
#### Is there a related issue for this PR? 
Issue number: #1195

### CODE REVIEW

**Comment by Joe-Winchester** [comment]
@NayerNajafi - i've written this chapter in draft mode - I've never set up USS before so this is mostly information that a customer told us on their prez.    Can you take a look and add more info to how to set up Java HEAP correctly,  information on OMVS segment site (I believe you've run into problems with customers where you needed to increase that) and all the other great nuggets you'v'e collected while you've supported Zowe customers and we can build up this chapter over time.   Feel free to just commit to the branch directly any updates you have

**Comment by NayerNajafi** [comment]
Hi @Joe-Winchester I've started providing/adding some information about OMVS segment and what user needs to consider while installing Zowe. The draft work is https://github.com/zowe/docs-site/pull/1228
Once completed, i will send for your review.

Thanks!

**Comment by Joe-Winchester** [comment]
@NayerNajafi - many thanks for your PR to the branch.  I've merged your changes and made a few formatting edits.  I can't add you as a formal reviewer because github knows you are one of the PR authors, but could you take a quick look to make sure it still reads well, and once you're happy then @nannanli can do a final check and hopefully this can get into 1.12 which will be great.

**Comment by NayerNajafi** [comment]
@Joe-Winchester sounds good to me. Thanks!

**Comment by nannanli** [comment]
@NayerNajafi @Joe-Winchester I edited this topic and added it to the TOC/left-hand navigation. Please review the latest one.

**Comment by Joe-Winchester** [comment]
@nannanli - this looks really good and thank you for adding it to the `pages.json` so it appears on the left hand bar.

**Comment by NayerNajafi** [comment]
@nannanli Thanks Ashley!

**Pull request merged**
