### PR TITLE
Refactor article formatting

### PR DESCRIPTION
**Pull request by janan07**
Article refactored to reflect changes in TLS security

### CODE REVIEW

**Comment by trode05** [comment]
Why all the words in titles are upper-cased? This approach does not seem to be consistent with the rest of articles.

**Comment by JamesBauman** [comment]
You are correct - Zowe doc standards are different from CA/Broadcom standards,  For Zowe, only the first word and names/proper nouns s/b capped, whereas CA all caps except forms of 'to be' (is, are, was, were) and prepositions less than 5 characters s/b lower case.

**Comment by janan07** [comment]
Ok. I'll correct the titles.

**Comment by trode05** [comment]
https://github.com/zowe/api-layer/blob/https-local-certmgmt-%2372/keystore/README.md link is broken

**Comment by trode05** [comment]
at the end, there is a reference to "https://github.com/zowe/api-layer/issues/91" which is closed already. Guess we could remove/fix it

**Comment by janan07** [comment]
The final heading with a broken link was removed. 

	Use an existing server certificate for API Mediation Layer
	
	This will be documented during work on the following user story: 
	https://github.com/zowe/api-layer/issues/91

**Comment by JamesBauman** [comment]
@janan07 - Andrew - There are conflicts preventing and automatic merge, so you might want to review the commit.
thx,
jb

**Pull request merged**
