### PR TITLE
Fix the incorrect script or file path

### PR DESCRIPTION
**Pull request by nannanli**
Signed-off-by: nannanli <nannanli@cn.ibm.com>

- Changed `/scripts/zowe-install.yaml` to `/scripts/configure/zowe-install.yaml`
- Changed `/scripts/zowe-configure.sh` to `/scripts/configure/zowe-configure.sh`.

### CODE REVIEW

**Comment by nannanli** [comment]
@John-A-Davies Per comment, more clarifications are added now. 
@stevenhorsman This PR fixes the directory paths of the `zowe-install.yaml` file and the `zowe-configure.sh` script for configuring the Zowe runtime. Would you please take a look at the changes as well and let me know if there is any problem? 
Thank you both!

**Comment by Joe-Winchester** [comment]
@nannanli - should this be merged into docs-staging and not master ?

**Comment by JamesBauman** [comment]
Hi @Joe-Winchester ... This issue is pending approval/review from @stevenhorsman.  We can merge to master as soon as it is approved.

**Comment by JamesBauman** [comment]
**IMPORTANT!**

**DO NOT** merge this PR at this time. Merge this PR **after** we merge the docs-staging branch to support the 1.5 release,

**Note:** the content changes in this PR are not reflected in the docs-staging branch.  If we merge now, and then merge doc-staging, the docs-staging merge will over-write this PR.

**Comment by JamesBauman** [comment]
@nannanli  - this is complete. we waited until 1.5 was published.  there were conflicts that needed to be resolved.  all should be good, but please dbl-check when you get a chance.

thx,
jb

**Pull request merged**
