### PR TITLE
Update systemrequirements-zosmf-lite.md

### PR DESCRIPTION
**Pull request by ArooshLele**
I removed the 3 bullets, namely:
- Microsoft Internet Explorer Version 11 or later.
- Microsoft Edge (Windows 10).
- Mozilla Firefox ESR Version 52 or later.

I added a link to a page in the IBM documentation. This page lists the browsers supported by zosmf.

Describe your pull request here:

List the file(s) included in this PR:

After creating the PR, follow the instructions in the comments.

### CODE REVIEW

**Review by 1000TurquoisePogs — APPROVED** [review]
Great change in my opinion due to not needing to claim zosmf's own requirements in our doc.

**Review by janan07 — APPROVED** [review]
Reviewed and edited by Doc squad

**Comment by ArooshLele** [comment]
The changes to the content have been approved.
There are no further changes to be done to the content as of now.
I am signing off on this Pull Request.

**Comment by ArooshLele** [comment]
The changes to the content have been approved.
There are no further changes to be done to the content as of now.
I am signing off on this Pull Request.

**Pull request merged**
