### PR TITLE
Update Zowe CLI Web Help for v1.27

### PR DESCRIPTION
**Pull request by awharn**
Signed-off-by: Andrew W. Harn <andrew.harn@broadcom.com>

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../docs/contribute/contributing.md) to this repository.

- [X] If the changes in this PR is part of the next future release, make this pull request against the **docs-staging** branch which will be published at the next release boundary. If the changes in this PR are part of the current release, use the default base branch, **master**. For more information about branches, see https://github.com/zowe/docs-site/tree/master#understanding-the-doc-branches. 
      
- [ ] If this PR relates to GitHub issues in `docs-site` or other repositories, please list in Description, prefixed with **close**, **fix** or **resolve** keywords.

### Description (including links to related git issues)
Please describe your pull request.

This pull request updates the Zowe CLI Web-Help content for the Zowe v1.27 release. Additionally, the pull request modifies the downloadable files Javascript on the main Zowe Docs page to provide a more intuitive experience. The Web-Help download link next to the `Online interactive version` link downloads the web-help ZIP instead of the PDF file, which is more clearly made available under the `PDF format` heading.

:heart:Thank you!

### CODE REVIEW

**Review by JamesBauman — APPROVED** [review]
OK
Signed-off-by: JamesBauman <james.bauman@broadcom.com>

**Comment by MikeBauerCA** [comment]
@awharn is there anything specific that you would like me to review? This PR changes a large number of files. If it is just to let me know that the web-help is being updated to include web-help of some Zowe Conformant Plug-ins, then please proceed 👍

**Comment by awharn** [comment]
I added you for quick review of DownloadableFiles.js, in particular the ZIP -> PDF change, and any discussion that might come up regarding that change.

**Comment by nannanli** [comment]
Hi all, we'll publish 1.27 tomorrow. I'll merge this PR for now but if you have any further updates to make, please continue to push to `docs-staging` before the end of day Jan 24. Thank you!

**Pull request merged**
