### PR TITLE
Update mvd-using.md to improve 3270 and VT entries

### PR DESCRIPTION
**Pull request by sipples**
Improves the 3270 and VT plug-in descriptions and makes them technically accurate, less confusing.

#### Is there a related issue for this PR? 
Issue number: #977

### CODE REVIEW

**Comment by nannanli** [comment]
@jasonenglish2039 @1000TurquoisePogs Hi Jason, Sean, could you review this PR? See issue #977 for the background of these changes. Thanks!

**Comment by jasonenglish2039** [comment]
@ajinrocket can you look into making these updates. They don't look too difficult, but ask me any questions.

**Comment by jasonenglish2039** [comment]
@1000TurquoisePogs this seems to me almost entirely a UI change. If I search the documentation for "TN3270" I get the simple description of the app (https://docs.zowe.org/stable/user-guide/mvd-using.html#tn3270), plus a couple of release notes. If I search on "3270" I get the plugin tutorial which refers to it (correctly, I think) as the "3270 Terminal application."

**Comment by nannanli** [comment]
@jasonenglish2039 @1000TurquoisePogs Agree with Jason. This requires a UI change by renaming `TN3270` to `3270 Terminal`. IMO, if the docs are not quoting the exact UI label name, such as `Click the TN3270 icon on the Zowe desktop`, it should be good to call it just the ·3270 terminal` in descriptions. UI change should be added as a work item for a future release.

**Comment by jasonenglish2039** [comment]
@sipples the changes you want to make here look fine to me, but @nannanli I do not think sipples can commit to directly to master right. They would need to change this to commit to docs-staging to get the edits into 1.9?

**Comment by nannanli** [comment]
@jasonenglish2039 Sorry for the late comment. As 1.9 has already been published, now it's ok to merge this to master directly. I'm going to merge this PR now but feel free to raise any concerns or comments if any.

**Comment by jasonenglish2039** [comment]
Merge it!

**Pull request merged**
