### PR TITLE
Article title change to reflect contents

### PR DESCRIPTION
**Pull request by pinpan**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../docs/contribute/contributing.md) to this repository.

- [ ] If the changes in this PR is part of the next future release, make this pull request against the **docs-staging** branch which will be published at the next release boundary. If the changes in this PR are part of the current release, use the default base branch, **master**. For more information about branches, see https://github.com/zowe/docs-site/tree/master#understanding-the-doc-branches. 
      
- [ ] If this PR relates to GitHub issues in `docs-site` or other repositories, please list in Description, prefixed with **close**, **fix** or **resolve** keywords.

### Description (including links to related git issues)
Please describe your pull request.

:heart:Thank you!

### CODE REVIEW

**Comment by samanthasusu** [comment]
Hi @pinpan, thank you for your review. I noticed this issue pointed to the guide that I published before. I'm wondering if you and @balhar-jakub both agree to place this page to the Extend section, if yes, I will move it. Thank you so much!

**Comment by samanthasusu** [comment]
Sorry I thought this was the Security Deployment Guide in the **Get Started** section. Please ignore my previous actions. Thanks!

**Review by janan07 — APPROVED** [review]
Looks good

**Comment by janan07** [comment]
Please change the target of this PR to the docs-staging branch.

**Pull request closed without merging**
