### PR TITLE
Fix typos and remove whitespaces

### PR DESCRIPTION
**Pull request by tapaswenipathak**
Fix https://github.com/zowe/docs-site/issues/630.

### CODE REVIEW

**Comment by nannanli** [comment]
@IgorCATech :-)

**Comment by IgorCATech** [comment]
Let me review

**Comment by tapaswenipathak** [comment]
I added my signed-off for DCO. Please lemme know if face any issues in merging against mainline branch!

**Comment by IgorCATech** [comment]
Hey, tapaswenipathak, sorry for the delay. I think it looks good and is ready to be merged. The only problem is that your branch is out of date now - which prevents us from merging. Let me take care of that, and I'll merge the branches

**Pull request merged**
