### PR TITLE
Release x509 client certificate auth documentation

### PR DESCRIPTION
**Pull request by jandadav**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../docs/contribute/contributing.md) to this repository.

- [ ] If the changes in this PR is part of the next future release, make this pull request against the **docs-staging** branch which will be published at the next release boundary. If the changes in this PR are part of the current release, use the default base branch, **master**. For more information about branches, see https://github.com/zowe/docs-site/tree/master#understanding-the-doc-branches. 
      
- [ ] If this PR relates to GitHub issues in `docs-site` or other repositories, please list in Description, prefixed with **close**, **fix** or **resolve** keywords.

### Description (including links to related git issues)
Please describe your pull request.

:heart:Thank you!

### CODE REVIEW

**Review by stevenhorsman — APPROVED** [review]
Looks fine. One thing I've spotted which isn't exactly related to this fix, but might be worth including:
- api-mediation-internal-configuration.md and discovery-service-configuration.md both still have references to the old component directory.

**Comment by jalel01** [comment]
Looks good. Perhaps instead of the final sentence 'It is expected that in a future release it will be made available as a fully supported feature.' i would have 'Client Certificate authentication will move out of Beta once test automation is fully implemented across different security systems.'

**Comment by jandadav** [comment]
> Looks fine. One thing I've spotted which isn't exactly related to this fix, but might be worth including:
> 
> * api-mediation-internal-configuration.md and discovery-service-configuration.md both still have references to the old component directory.

I will double check this, thanks.

**Comment by jandadav** [comment]
> Looks good. Perhaps instead of the final sentence 'It is expected that in a future release it will be made available as a fully supported feature.' i would have 'Client Certificate authentication will move out of Beta once test automation is fully implemented across different security systems.'

adjusted

**Review by janan07 — APPROVED** [review]
Reviewed and edited by tech info

**Pull request merged**
