### PR TITLE
Add scripts to auto-update typedoc and web help

### PR DESCRIPTION
**Pull request by t1m0thyj**
This PR adds Bash scripts to automatically update web help for Zowe CLI and typedoc for Zowe Node.js SDKs.

To use the scripts, first create a new branch for the changes you're about to make.
Then run the scripts from the root of the docs-site repo with the desired Zowe version (in `X.Y.Z` format). For example:
```
bash scripts/updateTypedoc.sh 1.28.1
```
```
bash scripts/updateWebHelp.sh 2.2.0
```
Finally, verify the changes made by the script. If they look good, commit and push the changes as you normally would.

### CODE REVIEW

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋

**Comment by t1m0thyj** [comment]
@JamesBauman Before we merge this PR, I have a question to make sure the scripts will behave correctly for the next Zowe release.

When the time comes to update web help for Zowe 2.3, which folder should be updated? `static/v2.3.x`, `static/stable`, or both?

**Review by JamesBauman — APPROVED** [review]

**Comment by JamesBauman** [comment]
HI Tim, 

For a current/new release, we update static/stable.  For an older/new release we update the release specific folder.   Does this help?

**Comment by t1m0thyj** [comment]
> For a current/new release, we update static/stable. For an older/new release we update the release specific folder. Does this help?

Thanks, this does help 🙂 I've updated the scripts to use the `static/stable` directory for the latest release.

In case we ever have a new Zowe v1 release in the future (1.29.x?), it is possible to override the output directory like this:
```
bash scripts/updateWebHelp.sh 1.29.0 static/v1.29.x
```

But for most scenarios, you shouldn't have to be concerned with specifying an output directory as the script will automagically determined for you 😛

**Review by zFernand0 — APPROVED** [review]
Thanks for updating the script! 
LGTM! 😋

**Pull request merged**
