### PR TITLE
update architecture view for ha

### PR DESCRIPTION
**Pull request by jackjia-ibm**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../docs/contribute/contributing.md) to this repository.

- [ ] If the changes in this PR is part of the next future release, make this pull request against the **docs-staging** branch which will be published at the next release boundary. If the changes in this PR are part of the current release, use the default base branch, **master**. For more information about branches, see https://github.com/zowe/docs-site/tree/master#understanding-the-doc-branches. 
      
- [ ] If this PR relates to GitHub issues in `docs-site` or other repositories, please list in Description, prefixed with **close**, **fix** or **resolve** keywords.

### Description (including links to related git issues)

Before Joe W has newer version of the HA architecture view, let's use what we have so far.

:heart:Thank you!

### CODE REVIEW

**Review by NayerNajafi — APPROVED** [review]
Thanks Jack

**Comment by nannanli** [comment]
@jackjia-ibm Hi Jack, do we have a source file that people could edit in the future? If yes, could you upload it in this PR as well for future maintenance? Thanks!

**Comment by jackjia-ibm** [comment]
@nannanli yes the original ppt is also uploaded.

**Review by nannanli — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
