### PR TITLE
Changed to enable debug mode introduction

### PR DESCRIPTION
**Pull request by ilkinabdullayev**
Debug mode changes

### CODE REVIEW

**Comment by IgorCATech** [comment]
Let me edit this a bit.

**Comment by IgorCATech** [comment]
@ilkinabdullayev Please, review the commented text inside the procedure, I'll need more information to complete the review+editing.

**Comment by IgorCATech** [comment]
@ilkinabdullayev Please, review 2 versions of the same procedure and choose one that you like more. Some edits might be required. I'm sure Tomaz will help you to make a choice and improve text, if necessary.

**Comment by ilkinabdullayev** [comment]
Thanks, guys for making better the documentation!

**Pull request merged**
