### PR TITLE
add must gather and breakdown troubleshooting

### PR DESCRIPTION
**Pull request by NakulManchanda**
Signed-off-by: Nakul Manchanda <nakul.manchanda@ibm.com>

### CODE REVIEW

**Comment by NakulManchanda** [comment]
still working on more changes - created this PR as placeholder

**Comment by NakulManchanda** [comment]
Hi any ideas to resolve this issue?

```[vuepress] No matching page found for sidebar item "/troubleshoot/troubleshoot-app-framework"```

converting single page into section with multiple pages.

Breaking down following section:
https://zowe.github.io/docs-site/latest/troubleshoot/troubleshoot-app-framework.html

**Comment by nannanli** [comment]
@NakulManchanda A new folder is created to contain the app framework topics so the following link 
`../user-guide/install-zos.html#manually-installing-the-zowe-cross-memory-server`

should be changed to: 
`../../user-guide/install-zos.html#manually-installing-the-zowe-cross-memory-server`

I fixed it already and this PR passes link validation now. : ）

**Comment by NakulManchanda** [comment]
@jasonenglish2039  @nannanli thanks for updating links, feel free to review and merge, will add more issues after this is merged

**Comment by jasonenglish2039** [comment]
Nakul, I did some editing in your branch. I will create a pull request.

**Comment by nannanli** [comment]
I made some tweaks as well: adding periods, update some links to use relative link, etc. Merging it.

**Pull request merged**
