### PR TITLE
Add missing block in AT-TLS configuration

### PR DESCRIPTION
**Pull request by pablocarle**
Describe your pull request here:

- Remove redundant table of contents from AT-TLS articles in v3 and v2.18 (already available in sidebar)
- Add missing block from inbound AT-TLS rules

List the file(s) included in this PR:
- docs/user-guide/configuring-at-tls-for-zowe-server.md
- versioned_docs/version-v2.18.x/user-guide/configuring-at-tls-for-zowe-server.md

### CODE REVIEW

**Comment by taban03** [comment]
I'd also add example of the `TTLSKeyringParms` parameter block that is currently missing in the doc. I.E.
```
{
    ...
    TTLSKeyringParmsRef ZoweKeyring
}

TTLSKeyringParms ZoweKeyring
{
  Keyring ZOWERING
}
```

**Comment by taban03** [comment]
I've also noted that `TTLSSignatureParms` is not documented anywhere. Is it always required?

**Comment by pablocarle** [comment]
> `TTLSSignatureParms`

I believe this can be removed, can you also confirm in your setup? We should aim at the simplest setup possible

**Comment by pablocarle** [comment]
> I'd also add example of the `TTLSKeyringParms` parameter block that is currently missing in the doc. I.E.
> 
> ```
> {
>     ...
>     TTLSKeyringParmsRef ZoweKeyring
> }
> 
> TTLSKeyringParms ZoweKeyring
> {
>   Keyring ZOWERING
> }
> ```

Thanks, I'll check this one and add it

**Comment by taban03** [comment]
```
TTLSConnectionAction ClientConnectionAction  
{  
  HandshakeRole Client  
  TTLSCipherParmsRef CipherParms  
  TTLSConnectionAdvancedParmsRef ConnectionAdvancedParms  
  CertificateLabel  
}
```
Is `CertificateLabel` required? Also, it looks it misses the value

**Review by janan07 — APPROVED** [review]
Reviewed and edited by doc squad

**Comment by taban03** [comment]
```
TTLSConnectionAdvancedParms ApimlClientX509ConnAdvParms
{
  ApplicationControlled Off
  CertificateLabel Zowe Server
  SecondaryMap Off
}
```
`ApplicationControlled Off` is missing in our internal setup. Maybe that won't be necessary.

**Comment by taban03** [comment]
`ClientEnvironmentAdvParms` example is missing too.

**Comment by pablocarle** [comment]
> `ClientEnvironmentAdvParms` and `ServerEnvironmentAdvParms` are also not documented.

these are documented in the full example

**Review by taban03 — APPROVED** [review]

**Pull request merged**
